src/Entity/Messages.php
<?php

namespace App\Entity;

use DateTime;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\MessagesRepository;

/**
 * @ORM\Entity(repositoryClass=MessagesRepository::class)
 */
class Messages
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre;

    /**
     * @ORM\Column(type="text")
     */
    private $message;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_read=0;

    /**
     * @ORM\ManyToOne(targetEntity=Utilisateur::class, inversedBy="sent")
     * @ORM\JoinColumn(nullable=false)
     */
    private $expediteur;

    /**
     * @ORM\ManyToOne(targetEntity=Utilisateur::class, inversedBy="received")
     * @ORM\JoinColumn(nullable=false)
     */
    private $destinataire;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $marque;

    /**
     * @ORM\ManyToOne(targetEntity=Saison::class, inversedBy="messages")
     */
    private $saison;

    public function __construct()
    {
        $this->created_at=new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(string $message): self
    {
        $this->message = $message;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getIsRead(): ?bool
    {
        return $this->is_read;
    }

    public function setIsRead(bool $is_read): self
    {
        $this->is_read = $is_read;

        return $this;
    }

    public function getExpediteur(): ?Utilisateur
    {
        return $this->expediteur;
    }

    public function setExpediteur(?Utilisateur $expediteur): self
    {
        $this->expediteur = $expediteur;

        return $this;
    }

    public function getDestinataire(): ?Utilisateur
    {
        return $this->destinataire;
    }

    public function setDestinataire(?Utilisateur $destinataire): self
    {
        $this->destinataire = $destinataire;

        return $this;
    }

    public function getMarque(): ?bool
    {
        return $this->marque;
    }

    public function setMarque(?bool $marque): self
    {
        $this->marque = $marque;

        return $this;
    }

    public function getSaison(): ?Saison
    {
        return $this->saison;
    }

    public function setSaison(?Saison $saison): self
    {
        $this->saison = $saison;

        return $this;
    }
}

src/Controller/Gestion/ActiviteController.php
<?php

namespace App\Controller\Gestion;

use App\Entity\Activite;
use App\Form\ActiviteType;
use App\Repository\TokenRepository;
use App\Repository\SaisonRepository;
use App\Repository\ActiviteRepository;
use App\SearchData\ActiviteData;
use App\SearchForm\ActiviteForm;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;


/**
 * @Route("/gestion/activite", name="gestion_activite")
 */
class ActiviteController extends AbstractController
{
    private $activiteRepository;
    private $entityManager;
    private $tokenRepository;

    public function __construct(ActiviteRepository $activiteRepository, EntityManagerInterface $entityManager, TokenRepository $tokenRepository)
    {
        $this->activiteRepository = $activiteRepository;
        $this->entityManager = $entityManager;
        $this->tokenRepository = $tokenRepository;
    }
    /**
     * @Route("/essai", name="_essai", methods={"GET"})
     */
    public function copyFile()
    {
        $origine = './assets/sauvegarde/site/';
        $destination = './assets/site/';
        $files = ['cirque', 'danse', 'escalade', 'foot', 'instruments', 'multi', 'theatre', 'yoga', 'yogabis'];
        foreach ($files as $file) {
            copy($origine . $file . '.jpg', $destination . $file . '.jpg');
        }

        return new Response('ok');
    }

    /**
     * @Route("/{id_saison}/index", name="_index", methods={"GET"})
     */
    public function index($id_saison, PaginatorInterface $paginator, Request $request, SaisonRepository $saisonRepository, ActiviteRepository $activiteRepository): Response
    {
        $data = new ActiviteData();
        $form = $this->createForm(ActiviteForm::class, $data);

        $form->handleRequest($request);
        $saison = $saisonRepository->find($id_saison);
        $essai = $activiteRepository->findByActiviteCriteria($saison, $data);
        $results = $essai->getResult();


        $activites = $paginator->paginate(
            $results,
            $request->query->getInt('page', 1),
            $data->nb
        );

        if (empty($activites)) {
            $this->addFlash('danger', 'Il n\'y a pas encore d\'activités crées');

            return $this->redirectToRoute('gestion');
        }
        return $this->render('gestion/activite/index.html.twig', [
            'saison' => $saison,
            'activites' => $activites,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/new", name="_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $activite = new Activite();
        $formActivite = $this->createForm(ActiviteType::class, $activite);
        $formActivite->handleRequest($request);

        if ($formActivite->isSubmitted() && $formActivite->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($activite);
            $entityManager->flush();
            $saison = $activite->getSaison();

            return $this->redirectToRoute('gestion_activite_index', ['id_saison' => $saison->getid()]);
        }

        return $this->render('gestion/activite/new.html.twig', [
            'activite' => $activite,
            'formActivite' => $formActivite->createView(),
        ]);
    }

    /**
     * @Route("/{id}/edit/{id_saison}", name="_edit", methods={"GET","POST"})
     */
    public function edit($id, $id_saison, Request $request, Activite $activite): Response
    {
        $formActivite = $this->createForm(ActiviteType::class, $activite);
        $formActivite->handleRequest($request);

        if ($formActivite->isSubmitted() && $formActivite->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('gestion_activite_index', ['id_saison' => $id_saison]);
        }

        return $this->render('gestion/activite/edit.html.twig', [
            'activite' => $activite,
            'formActivite' => $formActivite->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="_delete", methods={"POST"})
     */
    public function delete(Request $request, Activite $activite): Response
    {
        if ($this->isCsrfTokenValid('delete' . $activite->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($activite);
            $entityManager->flush();
        }
        $id_saison = $activite->getSaison()->getId();

        return $this->redirectToRoute('gestion_activite_index', ['id_saison' => $id_saison]);
    }

    /**
     * @Route("/certificat/{id}", name="_certificat", methods={"GET"})
     */
    public function certificat($id, ActiviteRepository $activiteRepository): Response
    {
        $activite = $activiteRepository->find($id);
        $activite->setCertificatObligatoire(($activite->getCertificatObligatoire() ? '0' : '1'));
        $em = $this->getDoctrine()->getManager();
        $em->persist($activite);
        $em->flush();
        $saison = $activite->getSaison();

        return $this->redirectToRoute('gestion_activite_index', ['id_saison' => $saison->getid()]);
    }

    /**
     * @Route("/condition/{id}", name="_condition", methods={"GET"})
     */
    public function condition($id, ActiviteRepository $activiteRepository): Response
    {
        $activite = $activiteRepository->find($id);
        $activite->setSousCondition(($activite->getSousCondition() ? '0' : '1'));
        $em = $this->getDoctrine()->getManager();
        $em->persist($activite);
        $em->flush();
        $saison = $activite->getSaison();

        return $this->redirectToRoute('gestion_activite_index', ['id_saison' => $saison->getid()]);
    }
    /**
     * @Route("/update-sous-condition/{id}", name="app_activite_update_sous_condition", methods={"GET"})
     * @IsGranted("ROLE_GESTION")
     */
    public function updateSousCondition(Request $request, $id): Response
    {
        $token = $request->query->get('token');

        // Vérifier le token
        if (!$this->isValidToken($token, $id)) {
            throw $this->createAccessDeniedException('Token invalide ou expiré.');
        }

        // Récupérer l'activité et mettre à jour le champ sousCondition
        $activite = $this->activiteRepository->find($id);
        if ($activite) {
            // Inverser la valeur de sousCondition
            $activite->setSousCondition(!$activite->getSousCondition());
            $this->entityManager->flush();

            // Message de succès
            $this->addFlash('success', 'L\'activité a été mise à jour avec succès.');
        } else {
            throw $this->createNotFoundException('Activité non trouvée.');
        }

        // Rediriger vers gestion_activite_index avec l'id de la saison
        $saisonId = $activite->getSaison()->getId();
        return $this->redirectToRoute('gestion_activite_index', ['id_saison' => $saisonId]);
    }

    private function isValidToken($token, $id)
    {
        // Implémentez la vérification du token ici
        // Vous pouvez utiliser une base de données ou un autre mécanisme de stockage sécurisé
        // Exemple simplifié, à remplacer par votre logique de vérification
        return true;
    }

    private function storeToken($token, $activiteId)
    {
        // Stockez le token dans votre base de données avec une expiration
        // Exemple simplifié
        $expiration = new \DateTime('+1 hour');
        // Code pour stocker le token, l'activiteId et l'expiration dans la base de données
    }
}

src/Controller/Gestion/BanqueController.php
<?php

namespace App\Controller\Gestion;

use App\Entity\Banque;
use App\Form\BanqueType;
use App\Repository\BanqueRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/gestion/banque", name="gestion_banque")
 */
class BanqueController extends AbstractController
{
    /**
     * @Route("/", name="_index", methods={"GET"})
     */
    public function index(BanqueRepository $banqueRepository): Response
    {
        return $this->render('gestion/banque/index.html.twig', [
            'banques' => $banqueRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $banque = new Banque();
        $formBanque = $this->createForm(BanqueType::class, $banque);
        $formBanque->handleRequest($request);

        if ($formBanque->isSubmitted() && $formBanque->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($banque);
            $entityManager->flush();

            return $this->redirectToRoute('gestion_banque_index');
        }

        return $this->render('gestion/banque/new.html.twig', [
            'banque' => $banque,
            'formBanque' => $formBanque->createView(),
        ]);
    }


    /**
     * @Route("/{id}/edit", name="_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Banque $banque): Response
    {
        $formBanque = $this->createForm(BanqueType::class, $banque);
        $formBanque->handleRequest($request);

        if ($formBanque->isSubmitted() && $formBanque->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('gestion_banque_index');
        }

        return $this->render('gestion/banque/edit.html.twig', [
            'banque' => $banque,
            'formBanque' => $formBanque->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="_delete", methods={"POST"})
     */
    public function delete(Request $request, Banque $banque): Response
    {
        if ($this->isCsrfTokenValid('delete'.$banque->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($banque);
            $entityManager->flush();
        }

        return $this->redirectToRoute('gestion_banque_index');
    }
}

src/Controller/Gestion/Boutique/BoutiqueController.php
<?php

namespace App\Controller\Gestion\Boutique;

use App\Repository\PaiementBoutiqueRepository;
use App\Repository\PurchaseRepository;
use App\Service\EnCours;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\UX\Chartjs\Builder\ChartBuilderInterface;
use Symfony\UX\Chartjs\Model\Chart;

class BoutiqueController extends AbstractController
{
    /**
     * @Route("gestion/boutique", name="gestion_boutique")
     */
    public function boutique(Request $request, EnCours $enCours, PaiementBoutiqueRepository $paiementBoutiqueRepository, PurchaseRepository $purchaseRepository, ChartBuilderInterface $chartBuilder): Response
    {
        // graphiquecommande

        $produit = [];
        $total=0;
        $saison = $enCours->saison();
        $purchases = $purchaseRepository->findBy(['saison' => $saison]);
        foreach ($purchases as $purchase) {
            foreach ($purchase->getPurchaseItems() as $item) {
                if (array_key_exists($item->getProductName(), $produit)) {
                    $produit[$item->getProductName()] += $item->getQuantity();
                } else {
                    $produit[$item->getProductName()] = $item->getQuantity();
                }
                $total+=$item->getTotal();
            }
        }
        $chartProduit = $chartBuilder->createChart(Chart::TYPE_BAR);
        $chartProduit->setData([
            'labels' => array_keys($produit),
            'datasets' => [
                [
                    'label' => 'Produit',
                    'backgroundColor' => 'rgb(209, 205, 206)',
                    'borderColor' => 'rgb(255, 99, 132)',
                    'data' => array_values($produit),
                ],
            ],
        ]);
        $chartProduit->setOptions([
            'scales' => [
                            'yAxes' => [
                                ['ticks' => ['min' => 0]],
                            ],
                        ],
        ]);

        $paiements=$paiementBoutiqueRepository->findBy(['saison'=>$saison]);
        $totalPaiement=0;
        foreach ($paiements as $paiement) {
            $totalPaiement+=$paiement->getMontant();
        }

        return $this->render('gestion/boutique/boutique.html.twig', [
            'purchases'=>$purchases,
            'totalPaiement'=>$totalPaiement,
            'total'=>$total,

            'chartProduit' => $chartProduit,
        ]);
    }
}

templates/gestion/message/__navbarMessage.html.twig
<ul class="nav">

	<li class="nav-item">
		<a class="nav-link" href="{{path("gestion_message_reception")}}">
			<i class="fas fa-envelope"></i>
			Boite de reception
			{% if messagesRepository.nonLu(app.user) > 0 %}
				<span class="badge rounded-pill bg-danger">{{messagesRepository.nonLu(app.user)}}</span>
			{% endif %}
		</a>
	</li>
	<li class="nav-item">
		<a class="nav-link" href="{{path("gestion_message_envoi")}}">
			<i class="fas fa-paper-plane"></i>
			Messages envoyés
			{% if messagesRepository.nonouvert(app.user) > 0 %}
				<span class="badge rounded-pill bg-danger">{{messagesRepository.nonouvert(app.user)}}</span>
			{% endif %}
		</a>
	</li>
	<li class="nav-item">

		<a class="nav-link active" aria-current="page" href="{{path("gestion_message_new")}}">
			<button class="btn btn-primary">
				<i class="fas fa-plus"></i>
				Nouveau message</button>

		</a>


	</li>
</ul>

templates/gestion/message/_envoi.html.twig
{% extends 'gestion/message/layoutMessage.html.twig' %}

{% block title %}Messagerie : Boite d'envoi'

{% endblock %}

{% block tableau %}
	<h5>Boite d'envoi</h5>

	<div class="table-responsive mb-4">
		<div id="toolbar" class="text-center">
			<button id="message" class="btn btn-secondary">Message</button>
		</div>
		<table id="envoi" data-toolbar="#toolbar" data-addrbar="true" data-cookie="true" data-cookie-id-table="envoi" data-toggle="table" data-show-fullscreen="true" data-show-export="true" data-page-size="15" data-page-list="[15,50, 100, all]" data-filter-control="true" data-show-search-clear-button="true" data-search="true" data-show-columns="true" data-pagination="true" data-click-to-select="true" data-show-columns-toggle-all="true" data-buttons="buttons" data-show-toggle="true" data-id-field="id" data-reorderable-columns="true">
			<thead>
				<tr>
					<th data-field="state" data-checkbox="true" data-print-ignore="true"></th>
					<th data-field="id" data-visible="false" data-print-ignore="true" data-sortable="true">id</th>
					<th data-field="a" data-visible="true">A :</th>
					<th data-field="sujet" data-visible="true">Sujet</th>
					<th data-field="date" data-visible="true">date</th>
					<th data-field="lu" data-visible="false" data-sortable="true" data-filter-control="select">Lu</th>
				</tr>
			</thead>
			<tbody>
				{% for message in messages %}
					{% if message.isRead ==0 %}
						{% set bold = "background-color:##b87509" %}

					{% else %}
						{% set bold = "" %}
					{% endif %}
					<tr style="{{bold}}">
						<td></td>
						<td>{{message.destinataire.id}}</td>

						<td>{{message.destinataire.nom ~ ' ' ~ message.destinataire.prenom}}</td>
						<td>
							<a href="{{path('gestion_message_envoi_show',{id : message.id })}}">{{message.titre}}</td>
						</td>

						<td>{{message.createdat|date("d/m/Y à H : i", "Europe/Paris")}}</td>
						<td>{{ message.isRead ? 'oui' : 'non' }}</td>
					</tr>

				{% endfor %}
			</tbody>
		</table>
	</div>
	{# <script>
	var $table = $( '#envoi' );
	function getRowSelections() {
	return $.map( $table.bootstrapTable( 'getSelections' ), function( row ) {
	return row;
	} )
	}
	
	
	$( '#message' ).click( function() {
	var selectedRows = getRowSelections();
	var selectedItems = '\n';
	let ids = [];
	$.each( selectedRows, function( index, value ) {
	ids.push( value.id );
	} );
	if ( ids.length ) {
	window.location.href = "/gestion/correspondance/message/" + ids.toString();
	} else {
	alert( 'Vous devez d\'abord selectionner une ligne' );
	}
	} );</script> #}
{% endblock %}
{# {% block javascripts %}{{parent()}}
<script src="https://cdn.jsdelivr.net/npm/jquery/dist/jquery.min.js"></script><script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script><script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script><script src="https://unpkg.com/tableexport.jquery.plugin/tableExport.min.js"></script><script src="https://cdn.jsdelivr.net/npm/jqueryui@1.11.1/jquery-ui.min.js"></script><script src="https://cdn.jsdelivr.net/gh/akottr/dragtable@master/jquery.dragtable.js"></script><script src="https://unpkg.com/bootstrap-table@1.18.3/dist/bootstrap-table.min.js"></script><script src="https://unpkg.com/bootstrap-table@1.18.3/dist/extensions/export/bootstrap-table-export.min.js"></script><script src="https://unpkg.com/bootstrap-table@1.18.3/dist/extensions/addrbar/bootstrap-table-addrbar.min.js"></script><script src="https://unpkg.com/bootstrap-table@1.18.3/dist/extensions/cookie/bootstrap-table-cookie.min.js"></script><script src="https://unpkg.com/bootstrap-table@1.16.0/dist/locale/bootstrap-table-fr-FR.min.js"></script><script src="https://unpkg.com/bootstrap-table@1.18.3/dist/extensions/filter-control/bootstrap-table-filter-control.min.js"></script><script src="https://unpkg.com/bootstrap-table@1.18.3/dist/extensions/reorder-columns/bootstrap-table-reorder-columns.min.js"></script>{% endblock %} #}

templates/gestion/message/_envoiShow.html.twig
{% extends 'gestion/message/layoutMessage.html.twig' %}

{% block title %}Messagerie : message

{% endblock %}

{% block tableau %}

	<div class="section">
		<div class="row">
			<div class="col-12">

				<h2>{{message.titre}}</h2>
				<p>Message de :
					{{message.destinataire.nom ~ ' ' ~ message.destinataire.prenom}}</p>
				<p>{{message.createdat|date("d/m/Y à H : i", "Europe/Paris")}}</p>

				<div>{{message.message|raw}}</div>

			</div>


		</div>
	</div>


{% endblock %}

templates/gestion/message/_layoutMessage.html.twig
{% extends 'utilisateur/layoutUtilisateur.html.twig' %}


{% block contenu %}
	<div class="paquet p-2">
		<div class="paquet-header">
			Messagerie
		</div>
		<div class="paquet-contenu">
			<div class="row">
				{% include "gestion/message/_navbarMessage.html.twig" %}</div>
			<div class="row">
				{% block tableau %}{% endblock %}
			</div>
		</div>
	</div>
{% endblock %}

templates/gestion/message/_new.html.twig
{% extends 'gestion/message/layoutMessage.html.twig' %}


{% block title %}Messagerie : Nouveau message

{% endblock %}

{% block tableau %}
	<h1>Nouveau message</h1>
	
	
	{{form_start(formMessage)}}
	{{form_end(formMessage)}}


{% endblock %}

templates/gestion/message/_reception.html.twig
{% extends 'gestion/message/layoutMessage.html.twig' %}

{% block title %}Messagerie : Boite de reception

{% endblock %}

{% block tableau %}
	<h5>Boîte de reception</h5>
	<div class="card shadow mb-4">
		<div class="card-body">
			<div class="table-responsive mb-4">
				<table id="reception" data-toolbar="#toolbar" data-addrbar="true" data-cookie="true" data-cookie-id-table="reception" data-toggle="table" data-show-fullscreen="true" data-show-export="true" data-page-size="15" data-page-list="[15, 50, 100, all]" data-filter-control="true" data-show-search-clear-button="true" data-search="true" data-show-columns="true" data-pagination="true" data-click-to-select="true" data-show-columns-toggle-all="true" data-buttons="buttons" data-show-toggle="true" data-id-field="id" data-reorderable-columns="true">
					<thead>
						<tr>
							<th data-field="marque" data-visible="true">Marqué</th>
							<th data-field="de" data-visible="true">De :</th>
							<th data-field="sujet" data-visible="true">Sujet</th>
							<th data-field="date" data-visible="true">date</th>
						</tr>
					</thead>
					<tbody>
						{% for message in messages %}
							{% if message.isRead ==0 %}
								{% set bold = "background-color:##b87509" %}

							{% else %}
								{% set bold = "" %}
							{% endif %}
							<tr style="{{bold}}">
								<td>
									{% if message.marque ==0 %}
										<i class="bi bi-star"></i>
									{% else %}
										<i class="bi bi-star-fill"></i>
									{% endif %}
								</td>
								<td>{{message.expediteur.nom ~ ' ' ~ message.expediteur.prenom}}</td>
								<td>
									<a href="{{path('gestion_message_reception_show',{id : message.id })}}">{{message.titre}}</td>
								</td>
								<td>{{message.createdat|date("d/m/Y à H : i", "Europe/Paris")}}</td>
							</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
		</div>
	</div>

{% endblock %}
{% block javascripts %}
	{{parent()}}
	<script src="https://cdn.jsdelivr.net/npm/jquery/dist/jquery.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
	<script src="https://unpkg.com/tableexport.jquery.plugin/tableExport.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/jqueryui@1.11.1/jquery-ui.min.js"></script>
	<script src="https://cdn.jsdelivr.net/gh/akottr/dragtable@master/jquery.dragtable.js"></script>
	<script src="https://unpkg.com/bootstrap-table@1.18.3/dist/bootstrap-table.min.js"></script>
	<script src="https://unpkg.com/bootstrap-table@1.18.3/dist/extensions/export/bootstrap-table-export.min.js"></script>
	<script src="https://unpkg.com/bootstrap-table@1.18.3/dist/extensions/addrbar/bootstrap-table-addrbar.min.js"></script>
	<script src="https://unpkg.com/bootstrap-table@1.18.3/dist/extensions/cookie/bootstrap-table-cookie.min.js"></script>
	<script src="https://unpkg.com/bootstrap-table@1.16.0/dist/locale/bootstrap-table-fr-FR.min.js"></script>
	<script src="https://unpkg.com/bootstrap-table@1.18.3/dist/extensions/filter-control/bootstrap-table-filter-control.min.js"></script>
	<script src="https://unpkg.com/bootstrap-table@1.18.3/dist/extensions/reorder-columns/bootstrap-table-reorder-columns.min.js"></script>

{% endblock %}

templates/gestion/message/_receptionShow.html.twig
{% extends 'gestion/message/layoutMessage.html.twig' %}

{% block title %}Messagerie : message

{% endblock %}

{% block tableau %}

	<div class="section">
		<div class="row">
			<div class="col-12">

				<h2>{{message.titre}}</h2>
				<div>
					<label class="form-switch mt-2">
						<input class="form-check-input marque" type="checkbox" {{ message.marque ? ' checked' : ' ' }} data-id="{{message.id}}">
						<span class="slider"></span>
					</label>
				</div>
				<p>Message de :
					{{message.expediteur.nom ~ ' ' ~ message.expediteur.prenom}}

					{% if dossier %}
						: <a href="{{ path('gestion_dossier_edit', {'id': dossier.id,'ancre': 'detail_none_none'}) }}">
							dossier en cours
						</a>
					{% endif %}

				</p>

				<p>{{message.createdat|date("d/m/Y à H : i", "Europe/Paris")}}</p>

				<div>{{message.message|raw}}</div>
				<a href="{{ path('gestion_message_repondre', {'id_destinaire': message.expediteur.id, 'titre': message.titre}) }}" class="btn btn-primary">Repondre</a>
			</div>

		</div>
	</div>


{% endblock %}
{% block javascripts %}
	{{parent()}}<script src="{{asset('assets/js/messageIndex.js')}}"></script>
{% endblock %}