src/Entity/Article.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use App\Repository\ArticleRepository;
use Gedmo\Mapping\Annotation as Gedmo;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass=ArticleRepository::class)
 * @Vich\Uploadable
 */
class Article
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre;

    /**
     * @Gedmo\Slug(fields={"titre"})
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(type="datetime_immutable")
     */
    private $created_at;

    /**
     * @ORM\Column(type="text")
     */
    private $contenu;

    /**
     * @ORM\ManyToOne(targetEntity=CategoryArticle::class, inversedBy="articles")
     * @ORM\JoinColumn(nullable=false)
     */
    private $categorie;

    /**
     * @ORM\ManyToOne(targetEntity=Menu::class, inversedBy="articles")
     */
    private $menu;

    /**
     * @Gedmo\Timestampable(on="update")
     * @ORM\Column(type="datetime_immutable")
     */
    private $updated_at;

    /**
     * NOTE: This is not a mapped field of entity metadata, just a simple property.
     *
     * @Vich\UploadableField(mapping="site_images", fileNameProperty="file")
     *
     * @var File|null
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $file;

    /**
     * @ORM\Column(type="boolean")
     */
    private $enLigne;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function getContenu(): ?string
    {
        return $this->contenu;
    }

    public function setContenu(string $contenu): self
    {
        $this->contenu = $contenu;

        return $this;
    }

    public function getCategorie(): ?CategoryArticle
    {
        return $this->categorie;
    }

    public function setCategorie(?CategoryArticle $categorie): self
    {
        $this->categorie = $categorie;

        return $this;
    }

    public function getMenu(): ?menu
    {
        return $this->menu;
    }

    public function setMenu(?menu $menu): self
    {
        $this->menu = $menu;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function getFile(): ?string
    {
        return $this->file;
    }

    public function setFile(string $file): self
    {
        $this->file = $file;

        return $this;
    }
    public function setImageFile(?File $file = null): void
    {
        $this->imageFile = $file;

        if (null !== $file) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updated_at = new \DateTimeImmutable();
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function getEnLigne(): ?bool
    {
        return $this->enLigne;
    }

    public function setEnLigne(bool $enLigne): self
    {
        $this->enLigne = $enLigne;

        return $this;
    }
}

src/Form/SiteType.php
<?php

namespace App\Form;

use App\Entity\Site;
use Symfony\Component\Form\AbstractType;
use Vich\UploaderBundle\Form\Type\VichFileType;
use Eckinox\TinymceBundle\Form\Type\TinymceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class SiteType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('slogan', TextType::class, [
                'label' => 'Votre slogan',
            ])
            ->add('description', TinymceType::class, [
                'label' => 'Description de vos activités',
            ])
            ->add('imageFile', VichFileType::class, [
                'label' => 'Choisir une photo pour ce produit',
                'required' => false,
                'allow_delete' => false,
                'download_uri' => false,

            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Site::class,
        ]);
    }
}

src/Controller/Gestion/Site/ArticleController.php
<?php

namespace App\Controller\Gestion\Site;

use App\Entity\Article;
use App\Form\ArticleType;
use App\SearchData\ArticleData;
use App\SearchForm\ArticleForm;
use App\Repository\ArticleRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

/**
 * @Route("gestion/site/article", name="gestion_site_article")
 */
class ArticleController extends AbstractController
{
    /**
     * @Route("/index", name="_index", methods={"GET"})
     */
    public function index(PaginatorInterface $paginator, Request $request, ArticleRepository $articleRepository): Response
    {
        $data = new ArticleData();
        $form = $this->createForm(ArticleForm::class, $data);
        $form->handleRequest($request);

        $articles = $paginator->paginate(
            $articleRepository->inscriptions($data),
            $request->query->getInt('page', 1),
            $data->nb
        );
        return $this->render('gestion/site/article/index.html.twig', [
            'articles' => $articles,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/new", name="_new", methods={"GET", "POST"})
     */
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $article = new Article();
        $form = $this->createForm(ArticleType::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($article);
            $entityManager->flush();

            return $this->redirectToRoute('gestion_site_article_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('gestion/site/article/new.html.twig', [
            'article' => $article,
            'form' => $form,
        ]);
    }


    /**
     * @Route("/{id}/edit", name="_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Article $article, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ArticleType::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('gestion_site_article_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('gestion/site/article/edit.html.twig', [
            'article' => $article,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/delete/{id}", name="_delete", methods={"POST"})
     */
    public function delete(Request $request, Article $article, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$article->getId(), $request->request->get('_token'))) {
            $entityManager->remove($article);
            $entityManager->flush();
        }

        return $this->redirectToRoute('gestion_site_article_index', [], Response::HTTP_SEE_OTHER);
    }
    /**
     * @Route("/enLigneGroupe/{ids}", name="_enLigneGroupe", methods={"GET"})
     */
    public function enLigneGroupe($ids, Request $request, ArticleRepository $articleRepository): Response
    {
        $referer = $request->headers->get('referer');
        $ids = explode(',', $ids);

        foreach ($ids as $id) {
            $article = $articleRepository->find($id);
            $article->setEnLigne(($article->getEnLigne() ? '0' : '1'));
            $em = $this->getDoctrine()->getManager();
        }
        $em->flush();


        return new Response('La mise en ligne des articles a changé d\'état', Response::HTTP_OK);
    }
}

src/Controller/Gestion/Site/MenuController.php
<?php

namespace App\Controller\Gestion\Site;

use App\Entity\Menu;
use App\Form\MenuType;
use App\Repository\MenuRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("gestion/site/menu", name="gestion_site_menu")
 */
class MenuController extends AbstractController
{
    /**
     * @Route("/", name="_index", methods={"GET"})
     */
    public function index(MenuRepository $menuRepository): Response
    {
        return $this->render('gestion/site/menu/index.html.twig', [
            'menus' => $menuRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="_new", methods={"GET", "POST"})
     */
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $menu = new Menu();
        $form = $this->createForm(MenuType::class, $menu);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($menu);
            $entityManager->flush();

            return $this->redirectToRoute('gestion_site_menu_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('gestion/site/menu/new.html.twig', [
            'menu' => $menu,
            'form' => $form,
        ]);
    }



    /**
     * @Route("/{id}/edit", name="_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Menu $menu, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(MenuType::class, $menu);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('gestion_site_menu_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('gestion/site/menu/edit.html.twig', [
            'menu' => $menu,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/delete/{id}", name="_delete", methods={"POST"})
     */
    public function delete(Request $request, Menu $menu, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$menu->getId(), $request->request->get('_token'))) {
            $entityManager->remove($menu);
            $entityManager->flush();
        }

        return $this->redirectToRoute('gestion_site_menu_index', [], Response::HTTP_SEE_OTHER);
    }
}

src/Controller/Gestion/Site/SiteController.php
<?php

namespace App\Controller\Gestion\Site;

use App\Entity\Site;
use App\Form\SiteType;
use App\Repository\SiteRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("gestion/site", name="gestion_site")
 */
class SiteController extends AbstractController
{
    /**
     * @Route("/edit", name="_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, EntityManagerInterface $entityManager, SiteRepository $siteRepository): Response
    {
        $site=$siteRepository->findOneBy([]);
        $form = $this->createForm(SiteType::class, $site);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('gestion_site_edit', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('gestion/site/edit.html.twig', [
            'site' => $site,
            'form' => $form,
        ]);
    }
}

src/Controller/Site/SiteController.php
<?php

namespace App\Controller\Site;

use App\Form\ContatType;
use App\Service\SendEmail;
use App\Entity\Utilisateur;
use App\Message\SendEmailMessage;
use App\Repository\MenuRepository;
use App\Repository\SiteRepository;
use App\Repository\SujetRepository;
use App\Repository\ArticleRepository;
use Doctrine\ORM\EntityManagerInterface;
use App\Repository\CategoryArticleRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Messenger\MessageBusInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class SiteController extends AbstractController
{
    /**
     * @Route("/", name="accueil", methods={"GET", "POST"})
     */
    public function accueil(Request $request, MessageBusInterface $messageBus, SendEmail $sendEmail, SujetRepository $sujetRepository, CategoryArticleRepository $categoryArticleRepository, EntityManagerInterface $entityManager, SiteRepository $siteRepository, MenuRepository $menuRepository, ArticleRepository $articleRepository): Response
    {
        $site = $siteRepository->findOneBy([]);
        $activite = $categoryArticleRepository->findBy(['nom' => 'Activité']);
        $activites = $articleRepository->findBy(['enLigne' => true, 'categorie' => $activite]);
        $actualite = $categoryArticleRepository->findBy(['nom' => 'Actualité']);
        $actualites = $articleRepository->findBy(['enLigne' => true, 'categorie' => $actualite], ['updated_at' => 'DESC'], 3);
        $menus = $menuRepository->findAll();
        $form = $this->createForm(ContatType::class);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $data = $form->getData();
            $sujet = $sujetRepository->findOneBy(['sujet' => 'Question divers']);
            /** @var Utilisateur $destinataire */
            $destinataire = $sujet->getDestinataire();
            $message = 'Vous avez recu un message de ' . $data['nom'] . '(' . $data['email'] . ') : ' . $data['message'];

            $sendEmail->send([
                'recipient_email' => $destinataire->getEmail(),
                'sujet' => $sujet->getSujet(),
                'htmlTemplate' => 'email/email.html.twig',
                'destinataire' => $destinataire,
                'context' => ['contenu' => $message],
            ]);

            return $this->redirectToRoute('accueil', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('site/accueil.html.twig', [
            'site' => $site,
            'activites' => $activites,
            'actualites' => $actualites,
            'menus' => $menus,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/menu/{id}", name="menu", methods={"GET", "POST"})
     */
    public function menu($id, Request $request, CategoryArticleRepository $categoryArticleRepository, SiteRepository $siteRepository, MenuRepository $menuRepository, ArticleRepository $articleRepository): Response
    {
        $site = $siteRepository->findOneBy([]);
        $menus = $menuRepository->findAll();
        $menu = $menuRepository->find($id);

        $activites = $articleRepository->findBy(['menu' => $menu]);

        return $this->renderForm('site/menu.html.twig', [
            'menu' => $menu,
            'site' => $site,
            'activites' => $activites,
            'menus' => $menus,
        ]);
    }

    /**
     * @Route("/actualite", name="actualite", methods={"GET", "POST"})
     */
    public function actualites(Request $request, CategoryArticleRepository $categoryArticleRepository, SiteRepository $siteRepository, MenuRepository $menuRepository, ArticleRepository $articleRepository): Response
    {
        $site = $siteRepository->findOneBy([]);
        $menus = $menuRepository->findAll();

        $actualite = $categoryArticleRepository->findBy(['nom' => 'Actualité']);
        $actualites = $articleRepository->findBy(['enLigne' => true, 'categorie' => $actualite], ['updated_at' => 'DESC']);

        return $this->renderForm('site/actualite.html.twig', [
            'site' => $site,
            'actualites' => $actualites,
            'menus' => $menus,
        ]);
    }

    /**
     * @Route("/article/{id}", name="article", methods={"GET", "POST"})
     */
    public function article($id, SiteRepository $siteRepository, MenuRepository $menuRepository, ArticleRepository $articleRepository): Response
    {
        $site = $siteRepository->findOneBy([]);
        $menus = $menuRepository->findAll();
        $article = $articleRepository->find($id);

        return $this->renderForm('site/article.html.twig', [
            'site' => $site,
            'article' => $article,
            'menus' => $menus,
        ]);
    }
}

templates/gestion/site/article/edit.html.twig
{% extends 'gestion/layoutGestionSite.html.twig' %}

{% block title %}Edition article
{% endblock %}

{% block sousElement %}
	<div class="paquet reduireL">
		<div class="paquet-header">
			<div class="card-header">{{article.titre}}

			</div>
		</div>
		<div class="paquet-contenu p-2">
			<div>
				{{form_start(form)}}
				<div class="row">
					<div class="col-12 col-md-6">{{form_row(form.titre)}}</div>
					<div class="col-12 col-md-6">{{form_row(form.enLigne)}}</div>
				</div>
				{{form_row(form.contenu)}}
				<div class="row">
					<div class="col">{{form_row(form.imageFile)}}

					</div>
					<div class="col">
						<p><img src="{{vich_uploader_asset(article,'imageFile')|imagine_filter('vignette')}}"></p>
					</div>
				</div>

				<div class="row">
					<div class="col">
						{{form_row(form.categorie)}}</div>
					<div class="col">{{form_row(form.menu)}}</div>
				</div>


				<div class="text-center">
					<button class="btn btn-primary btn" type="submit">Enregistrer</button>
					<a href="{{ path('gestion_site_article_index', {'id_saison': saisonEnCours.id }) }}">
						<button class="btn btn-secondary" type="button">Annuler</button>
					</a>
				</div>
				{{form_end(form)}}
			</div>


		</div>
	</div>

{% endblock %}

templates/gestion/site/article/index.html.twig
{% extends 'gestion/layoutGestionSite.html.twig' %}
{% block stylesheets %}

	{{parent()}}
	{{ encore_entry_link_tags('tableauFree') }}
{% endblock %}

{% block javascripts %}
	{{parent()}}
	{{ encore_entry_script_tags('tableauFree') }}
{% endblock %}
{% block title %}Liste des articles du site
{% endblock %}

{% block sousElement %}
	<h3>Liste de vos articles et activités</h3>
	<div id="toolbar" class="row">
		<div class="col">
			
				<button class="btn btn-primary" data-bs-toggle="offcanvas" data-bs-target="#filtre" role="button" data-bs-toggle=" tooltip" data-bs-placement=" top" title="Filtrer">
					FILTRER
				</button>
				<div class="offcanvas offcanvas-start lateral" tabindex="-1" id="filtre" data-bs-keyboard="false" data-bs-backdrop="false">
					<div class="offcanvas-header">
						<button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
					</div>
					<div class="offcanvas-body p-2">
						{{form_start(form)}}
						<div class="row">{{form_row(form.q)}}</div>
						<div class="row">{{form_row(form.categorie)}}</div>
						<div class="row">{{form_row(form.menu)}}</div>

						<div class="row">{{form_row(form.nb)}}</div>
						<button type="submit" class="btn btn-primary w-100">FILTRER</button>
						{{form_end(form)}}
					</div>
				</div>
			
				<a href="{{path('gestion_site_article_new') }}">
					<button class="btn btn-primary">Ajouter un nouvel article</button>
				</a>
			
		</div>
		<div class="col">
			<div class="p-1">
				<button id="enLigne" class="btn btn-secondary">En ligne</button>
			</div>
		</div>
	</div>
	<div class="row p-2">
		<div class="table-responsive">
			<table id="article" class="table table-hover">
				<thead>
					<tr>
						<th class="cache"></th>
						<th class="cache">id</th>
						<th>{{ knp_pagination_sortable(articles, 'Titre', 'a.titre') }}</th>
						<th>Image</th>
						<th>{{ knp_pagination_sortable(articles, 'Catégorie', 'c.nom') }}</th>
						<th>{{ knp_pagination_sortable(articles, 'Menu', 'm.nom') }}</th>
						<th>{{ knp_pagination_sortable(articles, 'crée le', 'a.createdAt') }}</th>
						<th>{{ knp_pagination_sortable(articles, 'modifié le', 'a.updateAt') }}</th>
						<th>{{ knp_pagination_sortable(articles, 'En ligne', 'a.enLigne') }}</th>
						<th></th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					{% for article in articles %}
						<tr>
							<td class="cache"></td>
							<td class="cache">{{article.id}}</td>
							<td>{{ article.titre }}</td>
							<td>
								<p><img src="{{vich_uploader_asset(article,'imageFile')|imagine_filter('vignette')}}"></p>
							</td>
							<td>{{article.categorie}}</td>
							<td>{{article.menu}}</td>
							<td>{{ article.createdAt ? article.createdAt|date("d/m/Y à H : i", "Europe/Paris")}}</td>
							<td>{{ article.createdAt ? article.updatedAt|date("d/m/Y à H : i", "Europe/Paris")}}</td>
							<td class="enLigne">
								{{ article.enLigne ? 'Oui' : 'Non' }}

							</td>
							<td>
								<a href="{{ path('gestion_site_article_edit', {'id': article.id}) }}">
									<button class="btn btn-primary">
										<i class="bi bi-pencil-square"></i>
									</button>
								</a>
							</td>
							<td>
								<form method="post" action="{{ path('gestion_site_article_delete', {'id': article.id} ) }}" onsubmit="return confirm('Etes-vous sur de vouloir supprimer cet article?');">
									<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ article.id) }}">
									<button class="btn btn-danger">
										<i class="bi bi-trash"></i>
									</button>
								</form>
							</td>

						</tr>
					{% else %}
						<tr>
							<td colspan="5">no records found</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
	</div>
{% endblock %}

templates/gestion/site/article/new.html.twig
{% extends 'gestion/layoutGestionSite.html.twig' %}

{% block title %}Nouvel article
{% endblock %}

{% block sousElement %}
	<div class="paquet reduireL">
		<div class="paquet-header">
			<div class="card-header">Nouvel article

			</div>
		</div>
		<div class="paquet-contenu p-2">
			<div>
				{{form_start(form)}}
				<div class="row">
					<div class="col-12 col-md-6">{{form_row(form.titre)}}</div>
					<div class="col-12 col-md-6">{{form_row(form.enLigne)}}</div>
				</div>
				{{form_row(form.contenu)}}
				{{form_row(form.imageFile)}}
				<div class="row">
					<div class="col">
						{{form_row(form.categorie)}}</div>
					<div class="col">{{form_row(form.menu)}}</div>
				</div>


				<div class="text-center">
					<button class="btn btn-primary btn" type="submit">Enregistrer</button>
					<a href="{{ path('gestion_site_article_index', {'id_saison': saisonEnCours.id }) }}">
						<button class="btn btn-secondary" type="button">Annuler</button>
					</a>
				</div>
				{{form_end(form)}}
			</div>


		</div>
	</div>


{% endblock %}